[versions]
# https://kotlinlang.org/docs/home.html
kotlin = "2.0.21"

# https://github.com/kotest/kotest
kotest = "5.9.1"

# https://axion-release-plugin.readthedocs.io/en/latest/
axion = "1.18.15"

# https://github.com/Kotlin/dokka
dokka = "1.9.20"

# https://opensource.deepmedia.io/deployer
deployer = "0.15.0"

[libraries]
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
axion = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion" }
deepmedia-deployer = { id = "io.deepmedia.tools.deployer", version.ref = "deployer" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
