[versions]
# https://kotlinlang.org/docs/home.html
kotlin = "2.0.21"
kotlinx-serialization = "1.7.3"
kotlinx-datetime = "0.6.1"

# https://www.slf4j.org/
slf4j = "2.0.16"

# https://logging.apache.org/log4j/2.x/index.html
log4j = "2.24.2"

# https://ktor.io/
ktor = "3.0.1"

# https://github.com/kotest/kotest
kotest = "5.9.1"

# https://axion-release-plugin.readthedocs.io/en/latest/
axion = "1.18.16"

# https://github.com/Kotlin/dokka
dokka = "1.9.20"

# https://opensource.deepmedia.io/deployer
deployer = "0.15.0"

# https://www.thymeleaf.org/
thymeleaf = "3.1.2.RELEASE"

# https://github.com/jhy/jsoup/
jsoup = "1.18.2"

# https://github.com/unicode-org/icu
icu4j = "76.1"

# https://javamoney.github.io/ri.html
moneta = "1.4.4"

# https://github.com/apollographql/apollo-kotlin
apollo = "4.1.0"

# https://github.com/graphql-java/graphql-java
graphql-java = "22.3"
gson = "2.11.0"

# https://github.com/h0tk3y/better-parse
better-parse = "0.4.4"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-test = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor"}

thymeleaf = { group = "org.thymeleaf", name = "thymeleaf", version.ref = "thymeleaf" }
icu4j = { group = "com.ibm.icu", name = "icu4j", version.ref = "icu4j" }
moneta = { group = "org.javamoney", name = "moneta", version.ref = "moneta" }
apollo-api = { module = "com.apollographql.apollo:apollo-api", version.ref = "apollo" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apollo-gradle-plugin = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo" }
graphql-java = { group = "com.graphql-java", name = "graphql-java", version.ref = "graphql-java" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
betterParse = { module = "com.github.h0tk3y.betterParse:better-parse", version.ref = "better-parse" }

slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
log4j-test = { module = "org.apache.logging.log4j:log4j-core-test", version.ref = "log4j" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
axion = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion" }
deepmedia-deployer = { id = "io.deepmedia.tools.deployer", version.ref = "deployer" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor"}
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
