package de.jakobschaefer.htma.graphql

import de.jakobschaefer.htma.HtmaRenderContext
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.runBlocking
import org.thymeleaf.context.ITemplateContext
import org.thymeleaf.engine.AttributeName
import org.thymeleaf.model.IProcessableElementTag
import org.thymeleaf.processor.element.AbstractAttributeTagProcessor
import org.thymeleaf.processor.element.IElementTagStructureHandler
import org.thymeleaf.templatemode.TemplateMode

// syntax:
// <variableName> = ~{ <ServiceName> :: <QueryName>(parameters...) }
class HtmaQueryAttributeProcessor(dialectPrefix: String) :
    AbstractAttributeTagProcessor(
        TemplateMode.HTML, dialectPrefix, null, false, "query", true, 10_000, true) {
  override fun doProcess(
      context: ITemplateContext,
      tag: IProcessableElementTag,
      attributeName: AttributeName,
      attributeValue: String,
      structureHandler: IElementTagStructureHandler
  ) {
    val htma = HtmaRenderContext.fromContext(context)
    val gqlExpr = GraphQlExpressionHelper.parseGraphQlExpression(attributeValue, context)
    val queries =
      runBlocking {
        gqlExpr.assignments
          .map { (variableName, queryRef) ->
            async {
              val result =
                if (htma.graphql.entries.containsKey(queryRef)) {
                  htma.graphql.entries[queryRef]
                } else {
                  // Construct the query class that has been generated by apollo from the markup and data.
                  val queryExecution = GraphQlExecution(
                    operation = queryRef,
                    context = context,
                    services = htma.graphqlServices,
                    cache = htma.graphql,
                  )
                  queryExecution.executeQueryAndCache()
                }
              variableName to result
            }
          }.awaitAll()
      }.toMap()

    for (query in queries) {
      structureHandler.setLocalVariable(query.key, query.value)
    }
  }
}

