name: Release
run-name: Release of ${{ github.ref_name }}
on:
  push:
    tags:
      - '*'
jobs:
  check:
    name: Check Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check project
        run: ./gradlew check

  publish-library:
    name: Publish htma-ktor-server library
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish to maven central
        run: |
          ./gradlew :htma-ktor-server:deployCentralPortal \
            -Pgpg.signing.key="${{ secrets.GPG_SIGNING_KEY }}" \
            -Pgpg.signing.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
            -PmavenCentral.portal.username="${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}" \
            -PmavenCentral.portal.password="${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}"

  publish-gradle-plugin:
    name: Publish de.jakobschaefer.htma gradle plugin
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish ktor-server-htma gradle-plugin
        run: |
          ./gradlew :htma-gradle-plugin:deployCentralPortal \
            -Pgpg.signing.key="${{ secrets.GPG_SIGNING_KEY }}" \
            -Pgpg.signing.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
            -PmavenCentral.portal.username="${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}" \
            -PmavenCentral.portal.password="${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}"
