name: Release
run-name: Release of ${{ github.ref_name }}
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Check project
        run: ./gradlew check
      - name: Publish ktor-server-htma library
        run: |
          ./gradlew :lib:deployCentralPortal \
            -Pgpg.signing.key="${{ secrets.GPG_SIGNING_KEY }}" \
            -Pgpg.signing.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
            -PmavenCentral.portal.username="${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}" \
            -PmavenCentral.portal.password="${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}"


